// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-server/internal/data/ent/account"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetAccount sets the "account" field.
func (ac *AccountCreate) SetAccount(s string) *AccountCreate {
	ac.mutation.SetAccount(s)
	return ac
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (ac *AccountCreate) SetNillableAccount(s *string) *AccountCreate {
	if s != nil {
		ac.SetAccount(*s)
	}
	return ac
}

// SetPwd sets the "pwd" field.
func (ac *AccountCreate) SetPwd(s string) *AccountCreate {
	ac.mutation.SetPwd(s)
	return ac
}

// SetNillablePwd sets the "pwd" field if the given value is not nil.
func (ac *AccountCreate) SetNillablePwd(s *string) *AccountCreate {
	if s != nil {
		ac.SetPwd(*s)
	}
	return ac
}

// SetNickname sets the "nickname" field.
func (ac *AccountCreate) SetNickname(s string) *AccountCreate {
	ac.mutation.SetNickname(s)
	return ac
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (ac *AccountCreate) SetNillableNickname(s *string) *AccountCreate {
	if s != nil {
		ac.SetNickname(*s)
	}
	return ac
}

// SetEmail sets the "email" field.
func (ac *AccountCreate) SetEmail(s string) *AccountCreate {
	ac.mutation.SetEmail(s)
	return ac
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ac *AccountCreate) SetNillableEmail(s *string) *AccountCreate {
	if s != nil {
		ac.SetEmail(*s)
	}
	return ac
}

// SetMobile sets the "mobile" field.
func (ac *AccountCreate) SetMobile(s string) *AccountCreate {
	ac.mutation.SetMobile(s)
	return ac
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (ac *AccountCreate) SetNillableMobile(s *string) *AccountCreate {
	if s != nil {
		ac.SetMobile(*s)
	}
	return ac
}

// SetCreateID sets the "create_id" field.
func (ac *AccountCreate) SetCreateID(i int64) *AccountCreate {
	ac.mutation.SetCreateID(i)
	return ac
}

// SetNillableCreateID sets the "create_id" field if the given value is not nil.
func (ac *AccountCreate) SetNillableCreateID(i *int64) *AccountCreate {
	if i != nil {
		ac.SetCreateID(*i)
	}
	return ac
}

// SetCreateTime sets the "create_time" field.
func (ac *AccountCreate) SetCreateTime(t time.Time) *AccountCreate {
	ac.mutation.SetCreateTime(t)
	return ac
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ac *AccountCreate) SetNillableCreateTime(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetCreateTime(*t)
	}
	return ac
}

// SetModifyID sets the "modify_id" field.
func (ac *AccountCreate) SetModifyID(i int64) *AccountCreate {
	ac.mutation.SetModifyID(i)
	return ac
}

// SetNillableModifyID sets the "modify_id" field if the given value is not nil.
func (ac *AccountCreate) SetNillableModifyID(i *int64) *AccountCreate {
	if i != nil {
		ac.SetModifyID(*i)
	}
	return ac
}

// SetModifyTime sets the "modify_time" field.
func (ac *AccountCreate) SetModifyTime(t time.Time) *AccountCreate {
	ac.mutation.SetModifyTime(t)
	return ac
}

// SetNillableModifyTime sets the "modify_time" field if the given value is not nil.
func (ac *AccountCreate) SetNillableModifyTime(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetModifyTime(*t)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AccountCreate) SetID(i int64) *AccountCreate {
	ac.mutation.SetID(i)
	return ac
}

// Mutation returns the AccountMutation object of the builder.
func (ac *AccountCreate) Mutation() *AccountMutation {
	return ac.mutation
}

// Save creates the Account in the database.
func (ac *AccountCreate) Save(ctx context.Context) (*Account, error) {
	ac.defaults()
	return withHooks[*Account, AccountMutation](ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AccountCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AccountCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AccountCreate) defaults() {
	if _, ok := ac.mutation.CreateTime(); !ok {
		v := account.DefaultCreateTime()
		ac.mutation.SetCreateTime(v)
	}
	if _, ok := ac.mutation.ModifyTime(); !ok {
		v := account.DefaultModifyTime()
		ac.mutation.SetModifyTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AccountCreate) check() error {
	return nil
}

func (ac *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Account(); ok {
		_spec.SetField(account.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := ac.mutation.Pwd(); ok {
		_spec.SetField(account.FieldPwd, field.TypeString, value)
		_node.Pwd = value
	}
	if value, ok := ac.mutation.Nickname(); ok {
		_spec.SetField(account.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := ac.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := ac.mutation.Mobile(); ok {
		_spec.SetField(account.FieldMobile, field.TypeString, value)
		_node.Mobile = value
	}
	if value, ok := ac.mutation.CreateID(); ok {
		_spec.SetField(account.FieldCreateID, field.TypeInt64, value)
		_node.CreateID = value
	}
	if value, ok := ac.mutation.CreateTime(); ok {
		_spec.SetField(account.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := ac.mutation.ModifyID(); ok {
		_spec.SetField(account.FieldModifyID, field.TypeInt64, value)
		_node.ModifyID = value
	}
	if value, ok := ac.mutation.ModifyTime(); ok {
		_spec.SetField(account.FieldModifyTime, field.TypeTime, value)
		_node.ModifyTime = value
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (acb *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Account, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
