// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-server/internal/data/ent/account"
	"go-server/internal/data/ent/article"
	"go-server/internal/data/ent/category"
	"go-server/internal/data/ent/schema"
	"go-server/internal/data/ent/website"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreateTime is the schema descriptor for create_time field.
	accountDescCreateTime := accountFields[7].Descriptor()
	// account.DefaultCreateTime holds the default value on creation for the create_time field.
	account.DefaultCreateTime = accountDescCreateTime.Default.(func() time.Time)
	// accountDescModifyTime is the schema descriptor for modify_time field.
	accountDescModifyTime := accountFields[9].Descriptor()
	// account.DefaultModifyTime holds the default value on creation for the modify_time field.
	account.DefaultModifyTime = accountDescModifyTime.Default.(func() time.Time)
	// account.UpdateDefaultModifyTime holds the default value on update for the modify_time field.
	account.UpdateDefaultModifyTime = accountDescModifyTime.UpdateDefault.(func() time.Time)
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescCreateTime is the schema descriptor for create_time field.
	articleDescCreateTime := articleFields[12].Descriptor()
	// article.DefaultCreateTime holds the default value on creation for the create_time field.
	article.DefaultCreateTime = articleDescCreateTime.Default.(func() time.Time)
	// articleDescModifyTime is the schema descriptor for modify_time field.
	articleDescModifyTime := articleFields[14].Descriptor()
	// article.DefaultModifyTime holds the default value on creation for the modify_time field.
	article.DefaultModifyTime = articleDescModifyTime.Default.(func() time.Time)
	// article.UpdateDefaultModifyTime holds the default value on update for the modify_time field.
	article.UpdateDefaultModifyTime = articleDescModifyTime.UpdateDefault.(func() time.Time)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreateTime is the schema descriptor for create_time field.
	categoryDescCreateTime := categoryFields[6].Descriptor()
	// category.DefaultCreateTime holds the default value on creation for the create_time field.
	category.DefaultCreateTime = categoryDescCreateTime.Default.(func() time.Time)
	// categoryDescModifyTime is the schema descriptor for modify_time field.
	categoryDescModifyTime := categoryFields[8].Descriptor()
	// category.DefaultModifyTime holds the default value on creation for the modify_time field.
	category.DefaultModifyTime = categoryDescModifyTime.Default.(func() time.Time)
	// category.UpdateDefaultModifyTime holds the default value on update for the modify_time field.
	category.UpdateDefaultModifyTime = categoryDescModifyTime.UpdateDefault.(func() time.Time)
	websiteFields := schema.Website{}.Fields()
	_ = websiteFields
	// websiteDescCreateTime is the schema descriptor for create_time field.
	websiteDescCreateTime := websiteFields[11].Descriptor()
	// website.DefaultCreateTime holds the default value on creation for the create_time field.
	website.DefaultCreateTime = websiteDescCreateTime.Default.(func() time.Time)
	// websiteDescModifyTime is the schema descriptor for modify_time field.
	websiteDescModifyTime := websiteFields[13].Descriptor()
	// website.DefaultModifyTime holds the default value on creation for the modify_time field.
	website.DefaultModifyTime = websiteDescModifyTime.Default.(func() time.Time)
	// website.UpdateDefaultModifyTime holds the default value on update for the modify_time field.
	website.UpdateDefaultModifyTime = websiteDescModifyTime.UpdateDefault.(func() time.Time)
}
