// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: realworld/v1/realworld.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RealWorld_SayHello_FullMethodName     = "/realoworld.v1.RealWorld/SayHello"
	RealWorld_WebSiteList_FullMethodName  = "/realoworld.v1.RealWorld/WebSiteList"
	RealWorld_WebSiteHome_FullMethodName  = "/realoworld.v1.RealWorld/WebSiteHome"
	RealWorld_CategoryList_FullMethodName = "/realoworld.v1.RealWorld/CategoryList"
)

// RealWorldClient is the client API for RealWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealWorldClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	WebSiteList(ctx context.Context, in *WebsiteRequest, opts ...grpc.CallOption) (*WebsiteReply, error)
	WebSiteHome(ctx context.Context, in *WebHomeRequest, opts ...grpc.CallOption) (*MultipleWebsiteReply, error)
	CategoryList(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*MultipleCategoryReply, error)
}

type realWorldClient struct {
	cc grpc.ClientConnInterface
}

func NewRealWorldClient(cc grpc.ClientConnInterface) RealWorldClient {
	return &realWorldClient{cc}
}

func (c *realWorldClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, RealWorld_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realWorldClient) WebSiteList(ctx context.Context, in *WebsiteRequest, opts ...grpc.CallOption) (*WebsiteReply, error) {
	out := new(WebsiteReply)
	err := c.cc.Invoke(ctx, RealWorld_WebSiteList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realWorldClient) WebSiteHome(ctx context.Context, in *WebHomeRequest, opts ...grpc.CallOption) (*MultipleWebsiteReply, error) {
	out := new(MultipleWebsiteReply)
	err := c.cc.Invoke(ctx, RealWorld_WebSiteHome_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realWorldClient) CategoryList(ctx context.Context, in *CategoryRequest, opts ...grpc.CallOption) (*MultipleCategoryReply, error) {
	out := new(MultipleCategoryReply)
	err := c.cc.Invoke(ctx, RealWorld_CategoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealWorldServer is the server API for RealWorld service.
// All implementations must embed UnimplementedRealWorldServer
// for forward compatibility
type RealWorldServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	WebSiteList(context.Context, *WebsiteRequest) (*WebsiteReply, error)
	WebSiteHome(context.Context, *WebHomeRequest) (*MultipleWebsiteReply, error)
	CategoryList(context.Context, *CategoryRequest) (*MultipleCategoryReply, error)
	mustEmbedUnimplementedRealWorldServer()
}

// UnimplementedRealWorldServer must be embedded to have forward compatible implementations.
type UnimplementedRealWorldServer struct {
}

func (UnimplementedRealWorldServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedRealWorldServer) WebSiteList(context.Context, *WebsiteRequest) (*WebsiteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebSiteList not implemented")
}
func (UnimplementedRealWorldServer) WebSiteHome(context.Context, *WebHomeRequest) (*MultipleWebsiteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WebSiteHome not implemented")
}
func (UnimplementedRealWorldServer) CategoryList(context.Context, *CategoryRequest) (*MultipleCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryList not implemented")
}
func (UnimplementedRealWorldServer) mustEmbedUnimplementedRealWorldServer() {}

// UnsafeRealWorldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealWorldServer will
// result in compilation errors.
type UnsafeRealWorldServer interface {
	mustEmbedUnimplementedRealWorldServer()
}

func RegisterRealWorldServer(s grpc.ServiceRegistrar, srv RealWorldServer) {
	s.RegisterService(&RealWorld_ServiceDesc, srv)
}

func _RealWorld_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealWorldServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealWorld_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealWorldServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealWorld_WebSiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebsiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealWorldServer).WebSiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealWorld_WebSiteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealWorldServer).WebSiteList(ctx, req.(*WebsiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealWorld_WebSiteHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealWorldServer).WebSiteHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealWorld_WebSiteHome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealWorldServer).WebSiteHome(ctx, req.(*WebHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealWorld_CategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealWorldServer).CategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealWorld_CategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealWorldServer).CategoryList(ctx, req.(*CategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RealWorld_ServiceDesc is the grpc.ServiceDesc for RealWorld service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealWorld_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "realoworld.v1.RealWorld",
	HandlerType: (*RealWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _RealWorld_SayHello_Handler,
		},
		{
			MethodName: "WebSiteList",
			Handler:    _RealWorld_WebSiteList_Handler,
		},
		{
			MethodName: "WebSiteHome",
			Handler:    _RealWorld_WebSiteHome_Handler,
		},
		{
			MethodName: "CategoryList",
			Handler:    _RealWorld_CategoryList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "realworld/v1/realworld.proto",
}
