// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Website is the predicate function for website builders.
type Website func(*sql.Selector)
