// Code generated by ent, DO NOT EDIT.

package category

import (
	"time"
)

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldCategoryName holds the string denoting the category_name field in the database.
	FieldCategoryName = "category_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreateID holds the string denoting the create_id field in the database.
	FieldCreateID = "create_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldModifyID holds the string denoting the modify_id field in the database.
	FieldModifyID = "modify_id"
	// FieldModifyTime holds the string denoting the modify_time field in the database.
	FieldModifyTime = "modify_time"
	// Table holds the table name of the category in the database.
	Table = "c_category"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldParentID,
	FieldCategoryID,
	FieldCategoryName,
	FieldStatus,
	FieldCreateID,
	FieldCreateTime,
	FieldModifyID,
	FieldModifyTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultModifyTime holds the default value on creation for the "modify_time" field.
	DefaultModifyTime func() time.Time
	// UpdateDefaultModifyTime holds the default value on update for the "modify_time" field.
	UpdateDefaultModifyTime func() time.Time
)
