// Code generated by ent, DO NOT EDIT.

package article

import (
	"time"
)

const (
	// Label holds the string label denoting the article type in the database.
	Label = "article"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSortID holds the string denoting the sort_id field in the database.
	FieldSortID = "sort_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldRecommend holds the string denoting the recommend field in the database.
	FieldRecommend = "recommend"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldContentBody holds the string denoting the content_body field in the database.
	FieldContentBody = "content_body"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldClickCount holds the string denoting the click_count field in the database.
	FieldClickCount = "click_count"
	// FieldLikeCount holds the string denoting the like_count field in the database.
	FieldLikeCount = "like_count"
	// FieldCreateID holds the string denoting the create_id field in the database.
	FieldCreateID = "create_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldModifyID holds the string denoting the modify_id field in the database.
	FieldModifyID = "modify_id"
	// FieldModifyTime holds the string denoting the modify_time field in the database.
	FieldModifyTime = "modify_time"
	// Table holds the table name of the article in the database.
	Table = "c_article"
)

// Columns holds all SQL columns for article fields.
var Columns = []string{
	FieldID,
	FieldSortID,
	FieldName,
	FieldCategoryID,
	FieldRecommend,
	FieldDescription,
	FieldContentBody,
	FieldImageURL,
	FieldStatus,
	FieldClickCount,
	FieldLikeCount,
	FieldCreateID,
	FieldCreateTime,
	FieldModifyID,
	FieldModifyTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultModifyTime holds the default value on creation for the "modify_time" field.
	DefaultModifyTime func() time.Time
	// UpdateDefaultModifyTime holds the default value on update for the "modify_time" field.
	UpdateDefaultModifyTime func() time.Time
)
