// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldPwd holds the string denoting the pwd field in the database.
	FieldPwd = "pwd"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldMobile holds the string denoting the mobile field in the database.
	FieldMobile = "mobile"
	// FieldCreateID holds the string denoting the create_id field in the database.
	FieldCreateID = "create_id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldModifyID holds the string denoting the modify_id field in the database.
	FieldModifyID = "modify_id"
	// FieldModifyTime holds the string denoting the modify_time field in the database.
	FieldModifyTime = "modify_time"
	// Table holds the table name of the account in the database.
	Table = "s_account"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldAccount,
	FieldPwd,
	FieldNickname,
	FieldEmail,
	FieldMobile,
	FieldCreateID,
	FieldCreateTime,
	FieldModifyID,
	FieldModifyTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultModifyTime holds the default value on creation for the "modify_time" field.
	DefaultModifyTime func() time.Time
	// UpdateDefaultModifyTime holds the default value on update for the "modify_time" field.
	UpdateDefaultModifyTime func() time.Time
)
